### ISSUE TITLE
How can i limit the space where it is shown?

### ISSUE THREAD

**Issue by MEANcisco** [sanchezweezer/Leaflet.webGlTemperatureMap#6]
Hello, i'm doing an integration of your library to a angular Leaflet map and i need some help about limit the space where it is shown.

I need to limit it to a drawn polygon so i can show the especified section of the layer on the heatmap, 
put some bounds to it can help me too, but i tried changing the bounds on the index unsuccessfully.

Thanks in advice

**Comment by sanchezweezer** [comment]
Hey, @MEANcisco 
thanks for your interest in my package :) I appreciate it. 

I faced a similar problem. I think the best solution (and the most productive) in such a situation would be to change the webGL algorithm by adding a new shader that would limit the scope.

However, the algorithm itself, in its pure form, does not provide for restrictions, and its calculation must still be made without restrictions, and later this mask should be applied to the canvas.

So far, I don't have enough time for this feature. I estimate it somewhere in two weeks of work. If you have the opportunity, I will be glad for help.

**Comment by MEANcisco** [comment]
Thanks!

Maybe i can give you the angular typing so you it can be imported on angular, how can i add a new shader for limit it? :o

**Comment by MEANcisco** [comment]
Hey!

Can i do it using Bounds? which file should i use to modify the shape of
the canvas?

Can you give me a example please, thanks in advice

**Comment by sanchezweezer** [comment]
No, you can't use Bounds from leaflet, because canvas cover all screen area and moves after map. 

Maybe you can make some kind of mask over the canvas, which would hide it. the right moments, but the problems of its positioning are not worth it.

The best thing is to add a similar mask directly to the canvas, it's just a matter of how to add it.

About files: 
src / index.js - responsible for integration with leaflet
src / temperature-map-idw.js - responsible for rendering the webGL scene


I think, if you just need something like Bounds - you should use webGL stencil. 
Check this - https://stackoverflow.com/questions/46806063/how-stencil-buffer-and-masking-work
And this one - https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/stencilFunc

**Comment by sanchezweezer** [comment]
or scissor (works like stencil, but it can be only rectangle area)

**Comment by sanchezweezer** [comment]
I start research, maybe in few days I can update lib or add some snippets right here.

**Comment by sanchezweezer** [comment]
<img width="1792" alt="Screenshot 2021-01-12 at 22 01 11" src="https://user-images.githubusercontent.com/19321990/104360231-ce65ec80-5521-11eb-9d02-2873a4f4faad.png">

Almost got it :) i think at the end of week i will end this, but i find bug with position on canvas on drag/zoom, next step is fix it

**Comment by sanchezweezer** [comment]
gets closer and closer...
<img width="1682" alt="Screenshot 2021-01-17 at 17 10 02" src="https://user-images.githubusercontent.com/19321990/104845531-00db6500-58e7-11eb-82ef-596265a31a6d.png">

**Comment by sanchezweezer** [comment]
publish new version - 0.2.0 check it if you still interesting in =)

**Comment by sanchezweezer** [comment]
update demo

**Comment by MEANcisco** [comment]
I never saw this! you are amazing! 
I'm trying this right now!

**Comment by sanchezweezer** [comment]
Wonderfull! Can I close this issue? :)

**Comment by diegosysagro** [comment]
Good afternoon, I'm trying to do the implementation but it just returns me a rectangle
![image](https://user-images.githubusercontent.com/92583434/155026520-104b49da-8edb-40f7-b799-d68761c63ff9.png)

export const mask = [
    [-23.6977264357896, -54.8964235559106],
    [-23.6922671559746, -54.9010999873281],
    [-23.6956839145134, -54.9039920791984],
    [-23.6995101235543, -54.9072321876884],
    [-23.7014917997076, -54.9053559824824],
    [-23.6994788094526, -54.9001226574183],
    [-23.6977264357896, -54.8964235559106],
];


const exp = [
  [-23.6995101235543, -54.9072321876884, 3],
  [-23.6994788094526, -54.9001226574183, 65]
];

export { exp };
